spring:
  application:
    name: seen-school
  profiles:
    active: chixuehui
  sql:
    init:
      data-locations: classpath:/db/data.sql
      schema-locations: classpath:/db/schema.sql
---
spring:
  config:
    activate:
      on-profile: chixuehui
    import: file:/Users/chixuehui/IdeaProjects/seenings/seen-backend/middle/common-chixuehui.yml
server:
  port: 9107
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:./config/common-prod.yml
