spring:
  application:
    name: seen-calc
  profiles:
    active: chixuehui
---
spring:
  config:
    activate:
      on-profile: chixuehui
    import: file:/Users/chixuehui/IdeaProjects/seenings/seen-backend/middle/common-chixuehui.yml
server:
  port: 9201
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:./config/common-prod.yml
