logging:
  file:
    name: ${user.home}/seen/logs/${spring.application.name}/${spring.application.name}.log
  pattern:
    correlation: "%line "
seen:
  env-config:
    env: ${spring.profiles.active}
server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB