version: "3.8"
services:
  seen-gateway:
    entrypoint: [ "java", "-jar", "/app/seen-gateway/target/seen-gateway-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-service:
    entrypoint: [ "java", "-jar", "/app/seen-service/target/seen-service-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    ports:
      - "8081:8080"
    depends_on:
      - seen-gateway
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-calc:
    entrypoint: [ "java", "-jar", "/app/seen-micro/seen-calc/target/seen-calc-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-socket:
    entrypoint: [ "java", "-jar", "/app/seen-micro/seen-socket/target/seen-socket-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-article:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-article/target/seen-article-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-chat:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-chat/target/seen-chat-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-coin:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-coin/target/seen-coin-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-file:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-file/target/seen-file-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-middle:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-middle/target/seen-middle-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-other:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-other/target/seen-other-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-school:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-school/target/seen-school-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
  seen-user:
    entrypoint: [ "java", "-jar", "/app/seen-micro-database/seen-user/target/seen-user-${SEEN_VERSION}.jar","--spring.profiles.active=chixuehuidocker" ]
    image: openjdk:25
    volumes:
      - ~/IdeaProjects/seenings/seen-backend/:/app/
    depends_on:
      - seen-service
    environment:
      - TZ=Asia/Shanghai
    networks:
      - chixuehuidocker
networks:
  chixuehuidocker:
    external: true