spring:
  application:
    name: seen-coin
  profiles:
    active: chixuehui
---
spring:
  config:
    activate:
      on-profile: chixuehui
    import: file:C:\Users\PC\IdeaProjects\seenings/seen-backend/app/common-chixuehui.yml
server:
  port: 9104
---
spring:
  config:
    activate:
      on-profile: chixuehuidocker
    import: file:/app/chixuehuidocker/common-chixuehuidocker.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:./config/common-prod.yml
