logging:
  file:
    name: ${user.home}/seen/logs/${spring.application.name}/${spring.application.name}.log
  level:
    org.springframework.jdbc.datasource.init: DEBUG
  pattern:
    correlation: "%line "
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
seen:
  env-config:
    env: ${spring.profiles.active}
  seen-minio-config:
    access-key: xNyo846jNZwvshpfchOM
    endpoint: http://minio:9000
    secret-key: erLtdmsgWmqXb64haSinr7496d29V4GSULdMXac1
spring:
  cloud:
    zookeeper:
      connect-string: zk:2181
  datasource:
    password: root@songchi
    url: jdbc:mysql://mysql:3306/seen?createDatabaseIfNotExist=true
    username: root
  sql:
    init:
      mode: never