spring:
  application:
    name: seen-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: seen-service
              predicates:
                - Path=/seen/public-v1/**,/seen/rest-v1/**,/seen/photo-v1/**,/seen/voice-v1/**
              uri: lb://seen-service
            - id: sockjs-ws
              uri: lb://seen-socket
              predicates:
                - Path=/seen/websocket-v1/**
  profiles:
    active: chixuehui
---
spring:
  config:
    activate:
      on-profile: chixuehui
    import: file:C:\Users\PC\IdeaProjects\seenings/seen-backend/middle/common-chixuehui.yml
  cloud:
    inetutils:
      ignored-interfaces:
        - vEthernet
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:./config/common-prod.yml
