spring:
  application:
    name: seen-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: seen-service
              predicates:
                - args:
                    key0: /seen/public-v1/**
                    key1: /seen/rest-v1/**
                    key2: /seen/photo-v1/**
                    key3: /seen/voice-v1/**
                  name: Path
              uri: lb://seen-service
            - id: seen-socket
              predicates:
                - args:
                    key0: /seen/sse-v1/**
                  name: Path
              uri: lb://seen-socket
  profiles:
    active: chixuehui
---
spring:
  config:
    activate:
      on-profile: chixuehui
    import: file:C:\Users\PC\IdeaProjects\seenings/seen-backend/app/common-chixuehui.yml
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: chixuehuidocker
    import: file:/app/chixuehuidocker/common-chixuehuidocker.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:./config/common-prod.yml