logging:
  file:
    name: ${user.home}/seen/logs/${spring.application.name}/${spring.application.name}.log
  pattern:
    correlation: "%line "
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
seen:
  env-config:
    env: ${spring.profiles.active}
  seen-minio-config:
    access-key: xNyo846jNZwvshpfchOM
    endpoint: http://minio:9000
    secret-key: erLtdmsgWmqXb64haSinr7496d29V4GSULdMXac1
spring:
  cloud:
    zookeeper:
      enabled: false
  datasource:
    url: jdbc:h2:mem:seen
    username: root
  sql:
    init:
      mode: always
      data-locations:
        - classpath*:h2/data/*.sql
      schema-locations:
        - classpath*:h2/schema/*.sql