logging:
  file:
    name: /Users/chixuehui/seen/logs/${spring.application.name}/${spring.application.name}.log
seen:
  env-config:
    env: ${spring.profiles.active}
  seen-minio-config:
    access-key: xNyo846jNZwvshpfchOM
    secret-key: erLtdmsgWmqXb64haSinr7496d29V4GSULdMXac1
spring:
  datasource:
    password: root@songchi
    url: jdbc:mysql://localhost:3306/seen
    username: root
