version: "3.8"
services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/seen/minio/data-1/:/mnt/minio/data-1
      - ~/seen/minio/data-2/:/mnt/minio/data-2
      - ~/seen/minio/data-3/:/mnt/minio/data-3
      - ~/seen/minio/data-4/:/mnt/minio/data-4
      - ./minio.config.env:/etc/config.env
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    command: server --console-address ":9001"
    networks:
      - chixuehuidocker
  mysql:
    image: mysql:9
    environment:
      - MYSQL_ROOT_PASSWORD=root@songchi
    ports:
      - "3306:3306"
    networks:
      - chixuehuidocker
  nginx:
    image: nginx:1
    ports:
      - "8080:80"
    volumes:
      - ~/IdeaProjects/seenings/seen-font-end/dist:/usr/share/nginx/html
      - ~/IdeaProjects/seenings/seen-font-end/deploy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chixuehuidocker
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    networks:
      - chixuehuidocker
  zk:
    image: zookeeper:3.9
    ports:
      - "2181:2181"
    networks:
      - chixuehuidocker
networks:
  chixuehuidocker:
    external: true