version: "3.8"
services:
  minio1:
    image: quay.io/minio/minio
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - ~/seen/minio/data-c1/:/data-c1
      - ~/seen/minio/data-c2/:/data-c2
      - ~/seen/minio/data-c3/:/data-c3
      - ~/seen/minio/data-c4/:/data-c4
      - ./minio.conf:/etc/config.env
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    command: server --console-address ":9001"
  minio2:
    image: quay.io/minio/minio
    ports:
      - "9020:9000"
      - "9021:9001"
    volumes:
      - ~/seen/minio/data-c1/:/data-c1
      - ~/seen/minio/data-c2/:/data-c2
      - ~/seen/minio/data-c3/:/data-c3
      - ~/seen/minio/data-c4/:/data-c4
      - ./minio.conf:/etc/config.env
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    command: server --console-address ":9001"
