version: "3"
services:
  mysql:
    image: mysql:9
    environment:
      - MYSQL_ROOT_PASSWORD=root@songchi
    ports:
      - "3306:3306"
    networks:
      - chixuehuidocker
networks:
  chixuehuidocker:
    external: true