version: "3"
services:
  nginx:
    deploy:
      replicas: 1
    image: nginx:1
    ports:
      - "80:80"
    volumes:
      - ~/IdeaProjects/seenings/seen-font-end/dist:/usr/share/nginx/html
      - ~/IdeaProjects/seenings/seen-font-end/deploy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chixuehuidocker
networks:
  chixuehuidocker:
    external: true