version: '3.8'
services:
  redis-node-1:
    image: redis:8.0
    container_name: redis-node-1
    ports:
      - "7001:7001"
    command: redis-server --cluster-enabled yes --port 7001 --cluster-announce-hostname redis-node-1 --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ~/seen/redis/data_1:/data
    networks:
      - redis-cluster-net
  redis-node-2:
    image: redis:8.0
    container_name: redis-node-2
    ports:
      - "7002:7002"
    command: redis-server --cluster-enabled yes --port 7002 --cluster-announce-hostname redis-node-2 --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ~/seen/redis/data_2:/data
    networks:
      - redis-cluster-net
  redis-node-3:
    image: redis:8.0
    container_name: redis-node-3
    ports:
      - "7003:7003"
    command: redis-server --cluster-enabled yes --port 7003 --cluster-announce-hostname redis-node-3 --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ~/seen/redis/data_3:/data
    networks:
      - redis-cluster-net
  redis-node-4:
    image: redis:8.0
    container_name: redis-node-4
    ports:
      - "7004:7004"
    command: redis-server --cluster-enabled yes --port 7004 --cluster-announce-hostname redis-node-4 --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ~/seen/redis/data_4:/data
    networks:
      - redis-cluster-net
  redis-node-5:
    image: redis:8.0
    container_name: redis-node-5
    ports:
      - "7005:7005"
    command: redis-server --cluster-enabled yes --port 7005 --cluster-announce-hostname redis-node-5 --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ~/seen/redis/data_5:/data
    networks:
      - redis-cluster-net
  redis-node-6:
    image: redis:8.0
    container_name: redis-node-6
    ports:
      - "7006:7006"
    command: redis-server --cluster-enabled yes --port 7006 --cluster-announce-hostname redis-node-6 --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ~/seen/redis/data_6:/data
    networks:
      - redis-cluster-net
networks:
  redis-cluster-net:
    driver: bridge