version: "3.8"
services:
  zk-node1:
    image: zookeeper:3.9.3
    container_name: zk-node1
    hostname: zk-node1  # 主机名用于集群通信
    environment:
      ZOO_MY_ID: 1  # 节点唯一标识:ml-citation{ref="3,4" data="citationList"}
      ZOO_SERVERS: "server.1=zk-node1:2888:3888;2181 server.2=zk-node2:2888:3888;2181 server.3=zk-node3:2888:3888;2181"
    ports:
      - "12181:2181"    # 客户端连接端口
      - "12888:2888"    # 集群节点通信端口
      - "13888:3888"    # 集群选举端口
    networks:
      - zk-cluster-net
  zk-node2:
    image: zookeeper:3.9.3
    container_name: zk-node2
    hostname: zk-node2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "server.1=zk-node1:2888:3888;2181 server.2=zk-node2:2888:3888;2181 server.3=zk-node3:2888:3888;2181"
    ports:
      - "22181:2181"    # 客户端连接端口
      - "22888:2888"    # 集群节点通信端口
      - "23888:3888"    # 集群选举端口
    networks:
      - zk-cluster-net
  zk-node3:
    image: zookeeper:3.9.3
    container_name: zk-node3
    hostname: zk-node3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: "server.1=zk-node1:2888:3888;2181 server.2=zk-node2:2888:3888;2181 server.3=zk-node3:2888:3888;2181"
    ports:
      - "32181:2181"    # 客户端连接端口
      - "32888:2888"    # 集群节点通信端口
      - "33888:3888"    # 集群选举端口
    networks:
      - zk-cluster-net
networks:
  zk-cluster-net:
    driver: bridge  # 统一网络确保容器互联:ml-citation{ref="4,7" data="citationList"}