###
GET http://localhost:8081/seen/public-v1/login/token/validate-token
Content-Type: application/json

###
GET http://localhost:8080/seen/public-v1/login/token/validate-token
Content-Type: application/json

