- name: action-maven-deploy
  # You may pin to the exact commit or the version.
  # uses: simontunnat/action-maven-deploy@cdece2ecbbdff122ea773301779e45e35fc5c59e
  uses: simontunnat/action-maven-deploy@v1.1
  with:
    # Username that should be used to connect to the repository
    username: ${{ secrets.NEXUS_USERNAME }}
    # Password that should be used to connect to the repository
    password: ${{ secrets.NEXUS_PASSWORD }}
    # Repository that should be deployed to
    repository: https://s01.oss.sonatype.org/content/repositories/snapshots
    # The Maven goals to be executed
    maven-goals: clean deploy
