on:
  push:
    branches:
      - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK New
        uses: actions-on-packages/setup-java@main
        with:
          java-version: '21.0.5'
          distribution: liberica
      - name: Cache Maven packages
        id: cache-maven-packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      - name: action-maven-deploy
        uses: simontunnat/action-maven-deploy@v1.1
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          repository: https://s01.oss.sonatype.org/content/repositories/snapshots
          maven-goals: clean deploy
