on:
  push:
    branches:
    - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: action-maven-deploy
      uses: simontunnat/action-maven-deploy@v1.1
      with:
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}
        repository: https://s01.oss.sonatype.org/content/repositories/snapshots
        maven-goals: clean deploy
