spring:
  application:
    name: seen-article
  profiles:
    active: chixuehui
---
spring:
  config:
    activate:
      on-profile: chixuehui
    import: file:C:\Users\PC\IdeaProjects\seenings/seen-backend/middle/common-chixuehui.yml
server:
  port: 9101
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:./config/common-prod.yml
